#!/usr/bin/env ruby
# frozen_string_literal: true

require 'keepasshttp'
require 'json'
require 'optparse'

params = {}
params[:key_store] = :auto
output_style = :json

ARGV.options do |opts| # rubocop:disable Metrics/BlockLength
  opts.banner = 'keepasshttp [options] URL [URL]'
  opts.on('-p INTEGER', '--port', 'Set the keepasshttp port [19422]') do |port|
    params[:port] = port.to_i
  end

  opts.on('--no-keystore', "Don't save the credentials") do
    params[:key_store] = false
  end

  opts.on('--plain', 'Use Keystore::Plain') do
    params[:key_store] = :Plain
  end

  opts.on('--ssh-agent', 'Use Keystore::SshAgent') do
    params[:key_store] = :SshAgent
  end

  opts.on('--token ID:KEY', 'Input your credentials') do |token|
    params[:key_store] ||= token
  end

  opts.on('--environment', 'Use the KEEPASSHTTP_CREDENTIALS variable') do
    params[:key_store] = :Environment
  end

  opts.on('-f', '--format STYLE', 'Choose output formater. [json]') do |style|
    output_style = style
  end

  opts.parse!

  if ARGV.empty?
    puts opts
    exit(1)
  end
end

begin
  puts Keepasshttp.connect(params).formatted_credentials_for(ARGV, output_style)
rescue StandardError => e
  warn e.message
  exit(1)
end
