#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'keepasshttp'
require 'json'
require 'optparse'

params = {}

ARGV.options do |opts|
  opts.on('-p INTEGER', '--port', 'Use Keystore::Plain') do |val|
    params[:port] = val.to_i
  end

  opts.on('--plain', 'Use Keystore::Plain') do
    params[:key_store] = :Plain
  end

  opts.parse!
end

puts Keepasshttp.connect(params).credentials_for(ARGV[0]).to_json
